language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn coveralls

before_deploy:
  - yarn build

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME